### ISSUE TITLE
Generate errors for the FlowMods

### ISSUE THREAD

**Issue by ajoaoff** [kytos-ng/flow_manager#1]
Original issue opened by @renanrodrigo at https://github.com/kytos/flow_manager/issues/23.

Such as malformed flow JSON or inexistent datapath

**Comment by viniarck** [comment]
@ajoaoff this has landed on PR #52, that made available the following events:

```
kytos/flow_manager.flow.removed
kytos/flow_manager.flow.added
```

and, in case of connection errors, it'll send a `kytos/flow_manager.flow.error` PR #60. 

Regarding the validations, we've got on our radar to handle on issue #43, so I think we can close this issue and handle the rest, that is the validation on this issue, wdyt? Once [your PR on `mef_eline`](https://github.com/kytos-ng/mef_eline/pull/90)  that addresses OAS and overall validation strategy, we can implement a similar approach when fixing the issue 43
