### ISSUE TITLE
Support for complex forwarding pipelines

### ISSUE THREAD

**Issue by ajoaoff** [kytos-ng/flow_manager#5]
Original issue opened by @jab1982 at https://github.com/kytos/flow_manager/issues/62.

Current Flow_manager Napp doesn't support complex forwarding pipelines, where more than one forwarding table is available. We need to find a way of expressing the pipeline we would like to use with a fallback option for switches that support a single forwarding table.

**Comment by viniarck** [comment]
`flow_manager` now has been supporting managing flows on multiple tables, we've also released a new NApp [of_multi_table](https://github.com/kytos-ng/of_multi_table) responsible for managing pipelines and specifying on which table which NApp should use.
