### ISSUE TITLE
Flows created outside Kytos should be removed by consistency check

### ISSUE THREAD

**Issue by ajoaoff** [kytos-ng/flow_manager#9]
Original issue opened by @ajoaoff at https://github.com/kytos/flow_manager/issues/113.

If a flow is created outside Kytos, it should be removed by the consistency check, but that is not happening.
Steps to reproduce:

- start kytos with a clean storehouse;
- start Mininet with a simple topology (e.g. linear with 3 switches);
- use OVS to install a flow (`ovs-ofctl add-flow s1 "<flow>"`);
- wait for the consistency check to run;
- verify that the flow is still installed.

**Comment by viniarck** [comment]
@ajoaoff the original failing test https://github.com/kytos/flow_manager/issues/113#issuecomment-802278446 doesn't fail anymore after the fixes that have landed over the past weeks, let me know if we can close this issue or if you'd like to add any other test case. 

```
============================= test session starts ==============================
...
tests/test_e2e_20_flow_manager.py ................                       [ 76%]
```
